version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - gocognit
    - errname
    - errorlint
    - noctx
    - prealloc
    - unconvert
    - unparam
  settings:
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
  exclusions:
    rules:
      - linters:
          - gocognit
          - unparam
          - goconst
        path: _test\.go

formatters:
  enable:
    - gofumpt
